options:
  site_name:                       
    type: string               
    description: Name of service shown in login screens and UI.
    default: "Mattermost"
  fqdn:                       
    type: string               
    description: FQDN of mattermost server to use. For example, 'mattermost.example.com'.
  port:
    type: int
    description: Nginx listen port
    default: 80
    
